spring:
  datasource:
    url: jdbc:mysql://localhost:3306/kanban
    username: 'kati'
    password: 'geheim'
  jpa:
    hibernate.ddl-auto: none
    show-sql: true
    generate-ddl: false
  thymeleaf:
    cache: false
  session:
    store-type: jdbc
    jdbc:
      initialize-schema: always
